/**
 * Filename: animdef.h
 * * Copyright (C) 1999-2005 Id Software, Inc.
 * Copyright (C) 2000-2010 FrozenSand
 *
 * This file is part of Urban Terror source code.
 *
 */
#define WEAPON_DRAW 							0
#define WEAPON_IDLE 							1
#define WEAPON_IDLE_EMPTY						2
#define WEAPON_IDLE_ALT 						3
#define WEAPON_IDLE_ALT_EMPTY					4
#define WEAPON_FIRE 							5
#define WEAPON_FIRE_ALT 						6
#define WEAPON_FIRE_LAST						7
#define WEAPON_RELOAD							8
#define WEAPON_RELOAD_START 					9
#define WEAPON_RELOAD_END						10
#define WEAPON_TOALTERNATE						11
#define WEAPON_TONORMAL 						12
#define WEAPON_READY_FIRE						13
#define WEAPON_READY_FIRE_ALT					14
#define WEAPON_READY_FIRE_IDLE					15
#define WEAPON_READY_FIRE_IDLE_ALT				16
#define WEAPON_BOLT 							17
#define WEAPON_FIRE_LAST_RIGHT					7
#define WEAPON_FIRE_LAST_LEFT					18
#define WEAPON_LASTROUND						19
#define MAX_WEAPON_ANIMATIONS					20
#define BOTH_LEDGECLIMB 						0
#define BOTH_WALLJUMP							1
#define BOTH_DEATH_BLOWBACK 					2
#define BOTH_DEAD_BLOWBACK						3
#define BOTH_DEATH_LEMMING						4
#define BOTH_DEAD_LEMMING						5
#define BOTH_DEATH_CHEST						6
#define BOTH_DEAD_CHEST 						7
#define BOTH_DEATH_HEADBACK 					8
#define BOTH_DEAD_HEADBACK						9
#define BOTH_DEATH_BLOWAHEAD					10
#define BOTH_DEAD_BLOWAHEAD 					11
#define BOTH_DEATH_HEADFRONT					12
#define BOTH_DEAD_HEADFRONT 					13
#define BOTH_DEATH_BACK 						14
#define BOTH_DEAD_BACK							15
#define BOTH_DEATH_CROUCHED 					16
#define BOTH_DEAD_CROUCHED						17
#define BOTH_DEATH_WATER						18
#define BOTH_DEAD_WATER 						19
#define BOTH_CLIMB								20
#define BOTH_CLIMB_IDLE 						21
#define LEGS_WALK								22
#define LEGS_BACKWALK							23
#define LEGS_BACKRUN							24
#define LEGS_SWIM								25
#define LEGS_JUMP								26
#define LEGS_LAND								27
#define LEGS_JUMPRT 							28
#define LEGS_LANDRT 							29
#define LEGS_BACKJUMP							30
#define LEGS_BACKLAND							31
#define LEGS_BACKJUMPRT 						32
#define LEGS_BACKLANDRT 						33
#define LEGS_LIMP								34
#define LEGS_BACKLIMP							35
#define LEGS_STANDCR							36
#define LEGS_CRSTAND							37
#define LEGS_RUN								38
#define LEGS_WALKCR 							39
#define LEGS_BACKWALKCR 						40
#define LEGS_IDLE								41
#define LEGS_IDLECR 							42
#define LEGS_SPRINT 							43
#define LEGS_TURN								44
#define TORSO_USE								45
#define TORSO_BANDAGE							46
#define TORSO_ATTACK_PISTOL 					47
#define TORSO_ATTACK_RIFLE						48
#define TORSO_ATTACK_SCOPE						49
#define TORSO_SCOPE 							50
#define TORSO_ATTACK_PUMPGUN					51
#define TORSO_ATTACK_GRENADE					52
#define TORSO_ATTACK_KNIFE						53
#define TORSO_WEAPON_LOWER						54
#define TORSO_WEAPON_RAISE						55
#define TORSO_RELOAD_PISTOL 					56
#define TORSO_RELOAD_RIFLE						57
#define TORSO_POINT 							58
#define TORSO_RUN_ATTACK_PISTOL 				59
#define TORSO_RUN_ATTACK_RIFLE					60
#define TORSO_RUN_ATTACK_PUMPGUN				61
#define TORSO_RUN_2HANDED						62
#define TORSO_RUN_1HANDED						63
#define TORSO_SWIM								64
#define TORSO_STAND_RIFLE						65
#define TORSO_STAND_PISTOL						66
#define TORSO_STAND_KNIFE						67
#define TORSO_STAND_CROUCH						68
#define TORSO_CROUCH_WALK						69
#define TORSO_STAND_WALK						70
#define TORSO_SECONDARY_CROUCH					71
#define TORSO_SECONDARY_STAND					72
#define TORSO_SECONDARY_ATTACK					73
#define TORSO_SECONDARY_RUN 					74
#define TORSO_SECONDARY_WALK					75
#define TORSO_SECONDARY_CROUCHWALK				76
#define TORSO_RUN_ATTACK_DUAL					77
#define TORSO_STAND_DUAL						78
#define TORSO_ATTACK_DUAL						79
#define MAX_PLAYER_ANIMATIONS					80
