name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  push:
    branches:
      - master
      - Quake3e-upstreammerge
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    name: Linux ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        include:
          - arch: x86
            use_sdl: USE_SDL=0

          - arch: x86_64
            use_sdl: USE_SDL=1

    steps:

    - name: Install tools
      run: |
        if [ "${{ matrix.arch }}" == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install gcc-multilib libcurl4-openssl-dev:i386 mesa-common-dev:i386 libxxf86dga-dev:i386 libxrandr-dev:i386 libxxf86vm-dev:i386 libasound-dev:i386
        else
          sudo apt-get -qq update
          sudo apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev
        fi

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) ARCH=${{ matrix.arch }} COMPILE_ARCH=${{ matrix.arch }} CC=gcc DESTDIR=bin ${{ matrix.use_sdl }} USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan CNAME=quake3e-vulkan BUILD_SERVER=0
        make clean ARCH=${{ matrix.arch }}
        make install -j$(nproc) ARCH=${{ matrix.arch }} COMPILE_ARCH=${{ matrix.arch }} CC=gcc DESTDIR=bin ${{ matrix.use_sdl }} USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=opengl

    - uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  windows-mingw:
    name: Windows-MinGW ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]

    steps:

    - name: Install MinGW
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install mingw-w64

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) ARCH=${{ matrix.arch }} DESTDIR=bin PLATFORM=mingw32 USE_SDL=0 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan CNAME=quake3e-vulkan BUILD_SERVER=0
        make clean ARCH=${{ matrix.arch }} PLATFORM=mingw32
        make install -j$(nproc) ARCH=${{ matrix.arch }} DESTDIR=bin PLATFORM=mingw32 USE_SDL=0 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=opengl

    - uses: actions/upload-artifact@v4
      with:
        name: windows-mingw-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  create-release:
    if: (contains(fromJSON('["master", "Quake3e-upstreammerge"]'), github.ref_name) && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    needs: [linux, windows-mingw]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create binary archives
        run: |
          mkdir -p client server
          for dir in linux-x86 linux-x86_64 windows-mingw-x86 windows-mingw-x86_64; do
            mkdir -p "client/$dir" "server/$dir"
            find "$dir" -type f -name '*quake3e.ded*' -exec cp {} "server/$dir/" \;
            find "$dir" -type f ! -name '*quake3e.ded*' -exec cp {} "client/$dir/" \;
          done
          7z a -r quake3e-subtick-client-${{ github.ref_name }}.zip ./client/*
          7z a -r quake3e-subtick-server-${{ github.ref_name }}.zip ./server/*

      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest-${{ github.ref_name }}"
          prerelease: false
          title: Latest Build (${{ github.ref_name }})
          files: |
            *.zip

  update-release:
    if: ${{ github.event_name == 'release' }}
    needs: [linux, windows-mingw]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - artifact_dir: linux-x86
            artifact_name: quake3e-subtick-linux-x86.zip

          - artifact_dir: linux-x86_64
            artifact_name: quake3e-subtick-linux-x86_64.zip

          - artifact_dir: windows-mingw-x86
            artifact_name: quake3e-subtick-windows-x86.zip

          - artifact_dir: windows-mingw-x86_64
            artifact_name: quake3e-subtick-windows-x86_64.zip

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create archive
        run: 7z a -r ${{ matrix.artifact_name }} ./${{ matrix.artifact_dir }}/*

      - name: Upload archive
        uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file: ${{ matrix.artifact_name }}
