name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-mingw:
    name: Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: ${{ matrix.prefix }}-binutils ${{ matrix.prefix }}-make ${{ matrix.prefix }}-gcc
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get build info
      id: build_info
      run: |
        echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        make install -j 8 ARCH=${{ matrix.arch }} CC=gcc DESTDIR=bin \
          USE_SDL=0 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan \
          CNAME="quake3e-${{ steps.build_info.outputs.date }}-${{ steps.build_info.outputs.sha }}" \
          DNAME="quake3e.ded-${{ steps.build_info.outputs.date }}-${{ steps.build_info.outputs.sha }}"

    - uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 14

  linux:
    name: Linux ${{ matrix.arch }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]

    steps:
    - name: Install tools
      run: |
        if [ "${{ matrix.arch }}" == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install gcc-multilib libcurl4-openssl-dev:i386 mesa-common-dev:i386 libxxf86dga-dev:i386 libxrandr-dev:i386 libxxf86vm-dev:i386 libasound-dev:i386
        else
          sudo apt-get -qq update
          sudo apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev
        fi

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get build info
      id: build_info
      run: |
        echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        make install -j 8 ARCH=${{ matrix.arch }} CC=gcc DESTDIR=bin \
          USE_SDL=0 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan \
          CNAME="quake3e-${{ steps.build_info.outputs.date }}-${{ steps.build_info.outputs.sha }}" \
          DNAME="quake3e.ded-${{ steps.build_info.outputs.date }}-${{ steps.build_info.outputs.sha }}"

    - uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 14

  create-release:
    if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    needs: [windows-mingw, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create binary archives
        run: |
          7z a -r quake3e-subtick-windows-x86.zip    ./windows-x86/*
          7z a -r quake3e-subtick-windows-x86_64.zip ./windows-x86_64/*
          7z a -r quake3e-subtick-linux-x86.zip      ./linux-x86/*
          7z a -r quake3e-subtick-linux-x86_64.zip   ./linux-x86_64/*

      - name: Create latest build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            *.zip

  update-release:
    if: github.event_name == 'release'
    needs: [windows-mingw, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create archives
        run: |
          7z a -r quake3e-subtick-windows-x86.zip    ./windows-x86/*
          7z a -r quake3e-subtick-windows-x86_64.zip ./windows-x86_64/*
          7z a -r quake3e-subtick-linux-x86.zip      ./linux-x86/*
          7z a -r quake3e-subtick-linux-x86_64.zip   ./linux-x86_64/*

      - name: Upload archives to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file: "*.zip"
          file_glob: true
